# Generated by Django 4.1.7 on 2023-03-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mohtava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('mabhas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.mabhas')),
            ],
            options={
                'verbose_name_plural': 'mohtavaha',
            },
        ),
    ]
